#!/bin/bash
# Generated by Copilot

################################################################################
# API helper functions for OpenCLI
# Author: Generated by Copilot
################################################################################

# Source common functions
source /usr/local/opencli/functions.sh

/**
 * Validates an API token and returns the associated username if valid
 *
 * @param {string} token - The API token to validate
 * @return {string} Username associated with token, or empty string if invalid
 */
validate_api_token() {
	local token="$1"

	if [ -z "$token" ]; then
		return 1
	fi

	# Database connection
	local DB_HOST=$(get_db_host)
	local DB_USER=$(get_db_user)
	local DB_PASS=$(get_db_password)
	local DB_NAME=$(get_db_name)

	# Check if token exists and is not expired
	local username=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -sN -e "
		SELECT username FROM api_tokens
		WHERE token='$token'
		AND expires_at > NOW()")

	if [ -n "$username" ]; then
		# Update last_used timestamp
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "
			UPDATE api_tokens
			SET last_used = NOW()
			WHERE token='$token'"

		echo "$username"
		return 0
	else
		return 1
	fi
}

/**
 * Extracts API token from Authorization header
 *
 * @param {string} authHeader - The Authorization header value
 * @return {string} The extracted token or empty string
 */
extract_token_from_header() {
	local authHeader="$1"

	if [[ "$authHeader" =~ ^Bearer\ +([A-Za-z0-9+/=_-]+)$ ]]; then
		echo "${BASH_REMATCH[1]}"
		return 0
	else
		return 1
	fi
}

/**
 * Sends a JSON response with appropriate HTTP headers
 *
 * @param {string} jsonData - The JSON data to send
 */
send_json_response() {
	local jsonData="$1"

	echo "Content-Type: application/json"
	echo ""
	echo "$jsonData"
}

/**
 * Sends an error response in JSON format
 *
 * @param {number} statusCode - HTTP status code
 * @param {string} message - Error message
 */
send_error_response() {
	local statusCode="$1"
	local message="$2"

	echo "Status: $statusCode"
	echo "Content-Type: application/json"
	echo ""
	echo "{\"error\": \"$message\", \"status\": $statusCode}"
}
