#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: functions/error_handling.sh
# Description: Error handling and logging functions for OpenCLI
# Author: Generated by Copilot
################################################################################

# Define color codes for error messages
ERROR_RED='\033[0;31m'
WARN_YELLOW='\033[0;33m'
INFO_BLUE='\033[0;34m'
SUCCESS_GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Default log directory
DEFAULT_LOG_DIR="/var/log/openpanel/admin"

# Default log files
ERROR_LOG="${DEFAULT_LOG_DIR}/errors.log"
ACCESS_LOG="${DEFAULT_LOG_DIR}/access.log"
DEBUG_LOG="${DEFAULT_LOG_DIR}/debug.log"

# Global debug flag
DEBUG_MODE=false

# Initialize logging
initLogging() {
	# Create log directory if it doesn't exist
	if [ ! -d "$DEFAULT_LOG_DIR" ]; then
		mkdir -p "$DEFAULT_LOG_DIR"
		chmod 755 "$DEFAULT_LOG_DIR"
	fi

	# Create log files if they don't exist
	touch "$ERROR_LOG"
	touch "$ACCESS_LOG"
	touch "$DEBUG_LOG"

	# Set permissions
	chmod 644 "$ERROR_LOG" "$ACCESS_LOG" "$DEBUG_LOG"
}

# Enable or disable debug mode
setDebugMode() {
	DEBUG_MODE="$1"
}

# Log an error message
logError() {
	local message="$1"
	local scriptName="${2:-unknown}"
	local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

	# Log to error log file
	echo "[$timestamp] ERROR [$scriptName] $message" >> "$ERROR_LOG"

	# Print to stderr
	echo -e "${ERROR_RED}Error:${NC} $message" >&2
}

# Log a warning message
logWarning() {
	local message="$1"
	local scriptName="${2:-unknown}"
	local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

	# Log to error log file
	echo "[$timestamp] WARNING [$scriptName] $message" >> "$ERROR_LOG"

	# Print to stderr
	echo -e "${WARN_YELLOW}Warning:${NC} $message" >&2
}

# Log an informational message
logInfo() {
	local message="$1"
	local scriptName="${2:-unknown}"
	local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

	# Log to access log
	echo "[$timestamp] INFO [$scriptName] $message" >> "$ACCESS_LOG"

	# Print to stdout
	echo -e "${INFO_BLUE}Info:${NC} $message"
}

# Log a success message
logSuccess() {
	local message="$1"
	local scriptName="${2:-unknown}"
	local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

	# Log to access log
	echo "[$timestamp] SUCCESS [$scriptName] $message" >> "$ACCESS_LOG"

	# Print to stdout
	echo -e "${SUCCESS_GREEN}Success:${NC} $message"
}

# Log a debug message (only if DEBUG_MODE is true)
logDebug() {
	if [ "$DEBUG_MODE" = true ]; then
		local message="$1"
		local scriptName="${2:-unknown}"
		local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

		# Log to debug log
		echo "[$timestamp] DEBUG [$scriptName] $message" >> "$DEBUG_LOG"

		# Print to stdout
		echo "DEBUG: $message"
	fi
}

# Handle an error and exit
exitWithError() {
	local message="$1"
	local exitCode="${2:-1}"
	local scriptName="${3:-unknown}"

	logError "$message" "$scriptName"
	exit "$exitCode"
}

# Check command execution status and handle errors
checkCommandStatus() {
	local exitCode=$?
	local command="$1"
	local errorMessage="${2:-Command failed}"
	local scriptName="${3:-unknown}"

	if [ $exitCode -ne 0 ]; then
		logError "$errorMessage (command: $command, exit code: $exitCode)" "$scriptName"
		return $exitCode
	fi

	return 0
}

# Validate that a required value is not empty
validateRequired() {
	local value="$1"
	local name="$2"
	local scriptName="${3:-unknown}"

	if [ -z "$value" ]; then
		logError "$name is required but was not provided" "$scriptName"
		return 1
	fi

	return 0
}

# Initialize logging by default when this library is sourced
initLogging
