#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: uninstall.sh
# Description: Uninstall OpenCLI completely from the system
# Usage: opencli uninstall [--purge] [--keep-backups] [--yes]
# Author: Generated by Copilot
# Created: $(date +%d.%m.%Y)
# Last Modified: $(date +%d.%m.%Y)
# Company: openpanel.com
# Copyright (c) openpanel.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
################################################################################

# Define color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
PURGE=false
KEEP_BACKUPS=false
ASSUME_YES=false
VERBOSE=false
OPENPANEL_INSTALLED=false

# Check if user is root
if [ "$(id -u)" -ne 0 ]; then
	echo -e "${RED}Error: This script must be run as root${NC}"
	exit 1
fi

# Parse command line arguments
while [[ $# -gt 0 ]]; do
	case "$1" in
		--purge)
			PURGE=true
			shift
			;;
		--keep-backups)
			KEEP_BACKUPS=true
			shift
			;;
		--yes)
			ASSUME_YES=true
			shift
			;;
		--verbose)
			VERBOSE=true
			shift
			;;
		--help)
			echo "Usage: opencli uninstall [OPTIONS]"
			echo ""
			echo "Options:"
			echo "  --purge         Remove all configuration files and user data"
			echo "  --keep-backups  Keep backup files (only with --purge)"
			echo "  --yes           Skip confirmation prompts"
			echo "  --verbose       Show detailed output during uninstallation"
			echo "  --help          Show this help message"
			echo ""
			exit 0
			;;
		*)
			echo -e "${RED}Error: Unknown option $1${NC}"
			echo "Use --help for usage information"
			exit 1
			;;
	esac
done

# Function to print status messages
print_status() {
	local status=$1
	local message=$2

	case "$status" in
		"info")
			echo -e "${BLUE}[INFO]${NC} $message"
			;;
		"ok")
			echo -e "${GREEN}[OK]${NC} $message"
			;;
		"warn")
			echo -e "${YELLOW}[WARNING]${NC} $message"
			;;
		"error")
			echo -e "${RED}[ERROR]${NC} $message"
			;;
	esac

	# Log to file if verbose
	if [ "$VERBOSE" = true ]; then
		echo "[$(date '+%Y-%m-%d %H:%M:%S')] $status: $message" >> "/var/log/openpanel/admin/uninstall.log"
	fi
}

# Function to validate critical paths before removal
validate_path() {
	local path="$1"
	local description="$2"

	# Ensure path is not empty
	if [ -z "$path" ]; then
		print_status "error" "Empty path provided for $description removal"
		return 1
	fi

	# Prevent removal of critical directories
	case "$path" in
		"/" | "/bin" | "/boot" | "/dev" | "/etc" | "/home" | "/lib" | "/lib64" | "/media" | "/mnt" | "/opt" | "/proc" | "/root" | "/run" | "/sbin" | "/srv" | "/sys" | "/tmp" | "/usr" | "/var")
			print_status "error" "Attempted to remove critical system directory: $path"
			return 1
			;;
	esac

	# Additional safeguard against dangerous paths
	if [[ ! "$path" =~ ^(/usr/local/opencli|/etc/openpanel|/var/log/openpanel|/tmp/opencli|/etc/nginx/sites-(available|enabled)/openpanel|/etc/cron.d/openpanel|/etc/systemd/system/admin.service) ]]; then
		print_status "error" "Attempted to remove unauthorized path: $path"
		return 1
	fi

	return 0
}

# Enhanced safe removal function
safe_remove() {
	local path="$1"
	local description="$2"
	local is_dir="${3:-false}"

	if validate_path "$path" "$description"; then
		if [ -e "$path" ]; then
			if [ "$is_dir" = "true" ]; then
				rm -rf "$path"
			else
				rm -f "$path"
			fi
			print_status "ok" "Removed $description"
		else
			if [ "$VERBOSE" = true ]; then
				print_status "info" "$description not found, skipping"
			fi
		fi
	else
		print_status "warn" "Skipping removal of $description for safety reasons"
	fi
}

# Function to check if OpenPanel is installed
check_openpanel() {
	if [ -f "/root/.env" ] && grep -q "openpanel" "/root/.env"; then
		OPENPANEL_INSTALLED=true
		print_status "info" "OpenPanel installation detected"
	fi
}

# Function to stop services
stop_services() {
	print_status "info" "Stopping OpenCLI services..."

	# Stop admin service
	if systemctl is-active admin >/dev/null 2>&1; then
		systemctl stop admin
		systemctl disable admin
		print_status "ok" "Stopped admin service"
	fi

	# Check if OpenPanel is installed
	if [ "$OPENPANEL_INSTALLED" = true ]; then
		if [ "$PURGE" = true ]; then
			print_status "warn" "OpenPanel is installed. Some components will be left intact unless you uninstall OpenPanel completely."
		else
			print_status "info" "OpenPanel is installed. Will only remove OpenCLI-specific components."
		fi
	fi
}

# Update remove_opencli_files to use safe removal
remove_opencli_files() {
	print_status "info" "Removing OpenCLI files..."

	# Remove OpenCLI script from path
	safe_remove "/usr/local/bin/opencli" "OpenCLI command"

	# Remove OpenCLI directory
	safe_remove "/usr/local/opencli" "OpenCLI directory" "true"
}

# Update remove_api_config to use safe removal
remove_api_config() {
	print_status "info" "Removing API configurations..."

	# Remove Nginx config for API
	safe_remove "/etc/nginx/sites-enabled/openpanel-api.conf" "API Nginx configuration symlink"
	safe_remove "/etc/nginx/sites-available/openpanel-api.conf" "API Nginx configuration file"

	# Reload Nginx if running
	if systemctl is-active nginx >/dev/null 2>&1; then
		systemctl reload nginx
		print_status "ok" "Reloaded Nginx configuration"
	fi
}

# Function to remove database tables
remove_database_tables() {
	if [ "$PURGE" = true ]; then
		print_status "info" "Removing OpenCLI database tables..."

		# Get database credentials
		if [ -f "/etc/openpanel/openpanel/conf/openpanel.config" ]; then
			DB_HOST=$(grep -E "^mysql_host=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)
			DB_USER=$(grep -E "^mysql_user=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)
			DB_PASS=$(grep -E "^mysql_password=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)
			DB_NAME=$(grep -E "^mysql_database=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)

			# Check if we have credentials
			if [ -n "$DB_HOST" ] && [ -n "$DB_USER" ] && [ -n "$DB_PASS" ] && [ -n "$DB_NAME" ]; then
				# Drop API tokens table
				mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "DROP TABLE IF EXISTS api_tokens"
				print_status "ok" "Removed API tokens table from database"
			else
				print_status "warn" "Could not retrieve database credentials, skipping database cleanup"
			fi
		else
			print_status "warn" "Configuration file not found, skipping database cleanup"
		fi
	fi
}

# Update remove_config_files to use safe removal
remove_config_files() {
	if [ "$PURGE" = true ]; then
		print_status "info" "Removing configuration files..."

		# Remove OpenCLI specific configurations
		safe_remove "/etc/openpanel/opencli" "OpenCLI configuration directory" "true"

		# Remove admin logs if they exist
		if [ "$VERBOSE" = true ]; then
			print_status "info" "Removing admin logs in /var/log/openpanel/admin"
		fi
		safe_remove "/var/log/openpanel/admin" "admin logs" "true"

		# Remove API documentation
		safe_remove "/etc/openpanel/openadmin/api" "API documentation files" "true"

		# If not keeping backups, remove backup configurations
		if [ "$KEEP_BACKUPS" = false ]; then
			safe_remove "/etc/openpanel/openadmin/config/backups" "backup configurations" "true"
		else
			print_status "info" "Keeping backup configurations as requested"
		fi
	else
		print_status "info" "Skipping removal of configuration files (use --purge to remove)"
	fi
}

# Update remove_temp_files to use safe removal
remove_temp_files() {
	print_status "info" "Cleaning up temporary files..."

	# Remove any temp files created by OpenCLI
	safe_remove "/tmp/opencli" "temporary OpenCLI files" "true"

	# Remove any temporary backup files
	if [ "$PURGE" = true ] && [ "$KEEP_BACKUPS" = false ]; then
		safe_remove "/tmp/openpanel_backups" "temporary backup files" "true"
	fi
}

# Function to detect and handle different Linux distributions
handle_distro_specific() {
	print_status "info" "Handling distribution-specific uninstallation..."

	# Detect Linux distribution
	if [ -f /etc/os-release ]; then
		. /etc/os-release
		DISTRO=$ID
	elif type lsb_release >/dev/null 2>&1; then
		DISTRO=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
	else
		DISTRO=$(uname -s)
	fi

	case "$DISTRO" in
		ubuntu|debian)
			# Handle Debian-based systems
			print_status "info" "Detected Debian-based system ($DISTRO)"

			# Check for APT packages
			if dpkg -l | grep -q "openpanel-cli"; then
				if [ "$PURGE" = true ]; then
					apt-get purge -y openpanel-cli
				else
					apt-get remove -y openpanel-cli
				fi
				print_status "ok" "Removed OpenCLI APT package"
			fi
			;;
		centos|rhel|fedora)
			# Handle RHEL-based systems
			print_status "info" "Detected RHEL-based system ($DISTRO)"

			# Check for RPM packages
			if rpm -qa | grep -q "openpanel-cli"; then
				yum remove -y openpanel-cli
				print_status "ok" "Removed OpenCLI RPM package"
			fi
			;;
		*)
			print_status "info" "Distribution-specific handling not implemented for $DISTRO"
			;;
	esac
}

# Update cleanup_system to use safe removal
cleanup_system() {
	print_status "info" "Cleaning up system components..."

	# Remove the systemd service file for admin
	safe_remove "/etc/systemd/system/admin.service" "admin service file"
	systemctl daemon-reload

	# Remove cron jobs related to OpenCLI
	safe_remove "/etc/cron.d/openpanel_backups" "backup cron jobs"

	# Remove bash completion
	if grep -q "opencli" /root/.bashrc; then
		sed -i '/opencli/d' /root/.bashrc
		print_status "ok" "Removed bash completion for OpenCLI"
	fi
}

# Add a backup function before uninstalling
create_backup() {
	if [ "$ASSUME_YES" = false ]; then
		read -p "Would you like to create a backup before uninstalling? [y/N] " -n 1 -r create_backup_reply
		echo ""
		if [[ $create_backup_reply =~ ^[Yy]$ ]]; then
			print_status "info" "Creating backup before uninstalling..."
			backup_dir="/tmp/opencli_backup_$(date +%Y%m%d_%H%M%S)"
			mkdir -p "$backup_dir"

			# Backup configuration files
			if [ -d "/etc/openpanel/opencli" ]; then
				cp -r "/etc/openpanel/opencli" "$backup_dir/"
				print_status "ok" "Backed up OpenCLI configuration"
			fi

			# Backup API tokens if database is accessible
			if [ -f "/etc/openpanel/openpanel/conf/openpanel.config" ]; then
				DB_HOST=$(grep -E "^mysql_host=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)
				DB_USER=$(grep -E "^mysql_user=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)
				DB_PASS=$(grep -E "^mysql_password=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)
				DB_NAME=$(grep -E "^mysql_database=" "/etc/openpanel/openpanel/conf/openpanel.config" | cut -d'=' -f2)

				if [ -n "$DB_HOST" ] && [ -n "$DB_USER" ] && [ -n "$DB_PASS" ] && [ -n "$DB_NAME" ]; then
					mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT * FROM api_tokens" > "$backup_dir/api_tokens.sql" 2>/dev/null
					if [ $? -eq 0 ]; then
						print_status "ok" "Backed up API tokens"
					fi
				fi
			fi

			# Create backup archive
			tar -czf "${backup_dir}.tar.gz" -C "$(dirname "$backup_dir")" "$(basename "$backup_dir")" && rm -rf "$backup_dir"
			print_status "ok" "Created backup archive: ${backup_dir}.tar.gz"
		fi
	fi
}

# Function to display completion message
completion_message() {
	echo ""
	echo -e "${GREEN}==================================================${NC}"

	if [ "$OPENPANEL_INSTALLED" = true ]; then
		echo -e "${GREEN}OpenCLI has been uninstalled.${NC}"
		echo ""
		if [ "$PURGE" = true ]; then
			echo -e "${YELLOW}Note: OpenPanel is still installed on this system.${NC}"
			echo -e "${YELLOW}To completely remove OpenPanel, run:${NC}"
			echo -e "  ${BLUE}cd /root && docker compose down${NC}"
			echo -e "  ${BLUE}rm -rf /etc/openpanel${NC}"
		else
			echo -e "${YELLOW}OpenPanel is still installed and functioning.${NC}"
			echo -e "${YELLOW}Only the OpenCLI command-line interface has been removed.${NC}"
		fi
	else
		echo -e "${GREEN}OpenCLI has been successfully uninstalled from your system.${NC}"
	fi

	echo -e "${GREEN}==================================================${NC}"
	echo ""
}

# Main execution function
main() {
	# Create log directory if verbose
	if [ "$VERBOSE" = true ]; then
		mkdir -p "/var/log/openpanel/admin"
		echo "=== OpenCLI Uninstall Log $(date) ===" > "/var/log/openpanel/admin/uninstall.log"
	fi

	echo -e "${BLUE}==================================================${NC}"
	echo -e "${BLUE}           OpenCLI Uninstallation Tool            ${NC}"
	echo -e "${BLUE}==================================================${NC}"
	echo ""

	# Check for OpenPanel installation
	check_openpanel

	# Display warning and confirmation
	if [ "$PURGE" = true ]; then
		echo -e "${YELLOW}Warning: You are about to uninstall OpenCLI with the --purge option.${NC}"
		echo -e "${YELLOW}This will remove all OpenCLI files, configurations, and database tables.${NC}"
		if [ "$KEEP_BACKUPS" = false ]; then
			echo -e "${YELLOW}Backup configurations will also be removed.${NC}"
		fi
	else
		echo -e "${YELLOW}You are about to uninstall OpenCLI from your system.${NC}"
		echo -e "${YELLOW}This will remove the OpenCLI command-line interface.${NC}"
	fi
	echo ""

	# Ask for confirmation unless --yes is provided
	if [ "$ASSUME_YES" = false ]; then
		read -p "Do you want to continue? [y/N] " -n 1 -r
		echo ""
		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
			echo -e "${RED}Uninstallation cancelled.${NC}"
			exit 1
		fi
	fi

	# Create backup if requested
	create_backup

	# Execute uninstallation steps
	stop_services
	remove_opencli_files
	remove_api_config
	remove_database_tables
	remove_config_files
	remove_temp_files
	handle_distro_specific
	cleanup_system

	# Final completion message
	completion_message
}

# Run the main function
main
