#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: tests/api_test.sh
# Description: Test OpenCLI API endpoints
# Author: Generated by Copilot
################################################################################

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Default settings
API_HOST="localhost"
API_PORT="8090"
API_TOKEN=""
VERBOSE=false
TESTS_PASSED=0
TESTS_FAILED=0
ERROR_LOG=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
	case "$1" in
		--host)
			API_HOST="$2"
			shift 2
			;;
		--port)
			API_PORT="$2"
			shift 2
			;;
		--token)
			API_TOKEN="$2"
			shift 2
			;;
		--verbose)
			VERBOSE=true
			shift
			;;
		--help)
			echo "Usage: api_test.sh [OPTIONS]"
			echo ""
			echo "Options:"
			echo "  --host HOST      API host (default: localhost)"
			echo "  --port PORT      API port (default: 8090)"
			echo "  --token TOKEN    API token for authentication"
			echo "  --verbose        Show detailed output including responses"
			echo "  --help           Show this help message"
			exit 0
			;;
		*)
			echo "Unknown option: $1"
			echo "Use --help for usage information"
			exit 1
			;;
	esac
done

if [ -z "$API_TOKEN" ]; then
	echo -e "${RED}Error: API token is required${NC}"
	echo "Generate a token using: opencli api-token-generate"
	echo "Then pass it with --token YOUR_TOKEN"
	exit 1
fi

# API base URL
API_BASE="http://${API_HOST}:${API_PORT}/api/v1"

# Function to make API requests
makeRequest() {
	local method="$1"
	local endpoint="$2"
	local data="$3"
	local url="${API_BASE}${endpoint}"

	local response
	if [ -n "$data" ]; then
		response=$(curl -s -X "$method" "$url" \
			-H "Authorization: Bearer $API_TOKEN" \
			-H "Content-Type: application/json" \
			-d "$data")
	else
		response=$(curl -s -X "$method" "$url" \
			-H "Authorization: Bearer $API_TOKEN")
	fi

	echo "$response"
}

# Function to run a test
runTest() {
	local name="$1"
	local method="$2"
	local endpoint="$3"
	local data="$4"
	local expectedStatus="$5"
	local expectedContent="$6"

	echo -e "\n${YELLOW}Testing ${method} ${endpoint}...${NC}"

	local response=$(makeRequest "$method" "$endpoint" "$data")

	if [ "$VERBOSE" = true ]; then
		echo "Response: $response"
	fi

	# Check if response contains expected content
	local testPassed=true
	if [ -n "$expectedContent" ] && ! echo "$response" | grep -q "$expectedContent"; then
		testPassed=false
		ERROR_LOG="${ERROR_LOG}\nTest '${name}' failed: Response does not contain '${expectedContent}'"
	fi

	# Check if response indicates expected status
	if [ -n "$expectedStatus" ]; then
		if [ "$expectedStatus" = "success" ] && ! echo "$response" | grep -q '"success":true' && ! echo "$response" | grep -q '"status":"ok"'; then
			testPassed=false
			ERROR_LOG="${ERROR_LOG}\nTest '${name}' failed: Response does not indicate success"
		elif [ "$expectedStatus" = "error" ] && ! echo "$response" | grep -q '"error"'; then
			testPassed=false
			ERROR_LOG="${ERROR_LOG}\nTest '${name}' failed: Response does not indicate error"
		fi
	fi

	if [ "$testPassed" = true ]; then
		echo -e "${GREEN}✓ Test '${name}' passed${NC}"
		TESTS_PASSED=$((TESTS_PASSED + 1))
	else
		echo -e "${RED}✗ Test '${name}' failed${NC}"
		TESTS_FAILED=$((TESTS_FAILED + 1))
	fi
}

# Start testing
echo -e "${YELLOW}Starting API tests against ${API_BASE}${NC}"

# Test system status endpoint
runTest "System status" "GET" "/system/status" "" "success" "uptime"

# Test domains endpoint
runTest "List domains" "GET" "/domains" "" "success" "domains"

# Test users endpoint
runTest "List users" "GET" "/users" "" "success" "users"

# Test plans endpoint
runTest "List plans" "GET" "/plans" "" "success" "plans"

# Test PHP versions endpoint
runTest "List PHP versions" "GET" "/php/versions" "" "success" "available_versions"

# Test invalid endpoint
runTest "Invalid endpoint" "GET" "/nonexistent" "" "error" "not found"

# Test with invalid token (save the original and restore after)
originalToken="$API_TOKEN"
API_TOKEN="invalid_token"
runTest "Invalid auth token" "GET" "/domains" "" "error" "Invalid or expired token"
API_TOKEN="$originalToken"

# Test services endpoint
runTest "Service control validation" "POST" "/system/services" '{"service":"invalid"}' "error" "Missing required parameters"

# Summary
echo -e "\n${YELLOW}Test Summary:${NC}"
echo -e "${GREEN}Tests passed: ${TESTS_PASSED}${NC}"
echo -e "${RED}Tests failed: ${TESTS_FAILED}${NC}"

if [ "$TESTS_FAILED" -gt 0 ]; then
	echo -e "\n${YELLOW}Failed tests:${NC}${RED}${ERROR_LOG}${NC}"
	exit 1
fi

exit 0
