#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: tests/test_api_token.sh
# Description: Test API token generation and validation
# Usage: bash test_api_token.sh
# Author: Generated by Copilot
################################################################################

# Set up colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

echo "=================================================="
echo "Testing API token functionality"
echo "=================================================="

# Test token generation
echo -e "${YELLOW}Testing token generation${NC}"

# Generate a token for current user
TOKEN=$(opencli api-token-generate | grep "Token:" | cut -d' ' -f2)

if [ -n "$TOKEN" ]; then
	echo -e "${GREEN}✓ Token generated successfully: ${TOKEN}${NC}"
else
	echo -e "${RED}✗ Failed to generate token${NC}"
	exit 1
fi

# Test a simple API call using the token
echo -e "\n${YELLOW}Testing API call with token${NC}"

# Create a temporary file for API response
RESPONSE=$(mktemp)

# Make API request using curl
curl -s -H "Authorization: Bearer $TOKEN" \
	"http://localhost/api/v1/domains" > "$RESPONSE"

# Check if response looks like JSON
if grep -q '{"domains":' "$RESPONSE"; then
	echo -e "${GREEN}✓ API call successful${NC}"
	echo "Sample response:"
	head -n 10 "$RESPONSE"
else
	echo -e "${RED}✗ API call failed or returned unexpected format${NC}"
	cat "$RESPONSE"
fi

# Clean up
rm -f "$RESPONSE"

echo "=================================================="
echo "API token tests completed"
echo "=================================================="
