#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: tests/test_domains_list.sh
# Description: Test the domains-list command functionality
# Usage: bash test_domains_list.sh
# Author: Generated by Copilot
################################################################################

# Set up colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Test function
runTest() {
	local testName="$1"
	local command="$2"
	local expectedExitCode="$3"

	echo -e "${YELLOW}Running test: $testName${NC}"
	echo "Command: $command"

	# Run the command and capture exit code
	eval "$command"
	local actualExitCode=$?

	# Check if exit code matches expected
	if [ $actualExitCode -eq $expectedExitCode ]; then
		echo -e "${GREEN}✓ Test passed (Exit code: $actualExitCode)${NC}"
		return 0
	else
		echo -e "${RED}✗ Test failed (Expected: $expectedExitCode, Got: $actualExitCode)${NC}"
		return 1
	fi
}

# Run tests
echo "==============================================="
echo "Testing domains-list command"
echo "==============================================="

# Test 1: Basic usage
runTest "Basic usage" "opencli domains-list" 0

# Test 2: JSON format
runTest "JSON format" "opencli domains-list --format json" 0

# Test 3: Simple format
runTest "Simple format" "opencli domains-list --format simple" 0

# Test 4: Filter by user
runTest "Filter by user" "opencli domains-list --user admin" 0

# Test 5: Help message
runTest "Help message" "opencli domains-list --help" 0

# Test 6: Invalid option
runTest "Invalid option (should fail)" "opencli domains-list --invalid" 1

echo "==============================================="
echo "Tests completed"
echo "==============================================="
