#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: tests/test_domains_formats.sh
# Description: Test all output formats of domains-list command
# Usage: bash test_domains_formats.sh
# Author: Generated by Copilot
################################################################################

# Set up colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Test function
runFormatTest() {
	local formatName="$1"
	local formatFlag="$2"

	echo -e "${YELLOW}Testing format: $formatName${NC}"

	# Create temporary file for output
	tempFile=$(mktemp)

	# Run command and capture output
	opencli domains-list --format "$formatFlag" > "$tempFile" 2>&1
	exitCode=$?

	# Check exit code
	if [ $exitCode -eq 0 ]; then
		echo -e "${GREEN}✓ Command executed successfully${NC}"

		# Display sample of output (first 5 lines)
		echo -e "${YELLOW}Sample output:${NC}"
		head -n 5 "$tempFile"

		# Check if output is not empty
		if [ -s "$tempFile" ]; then
			echo -e "${GREEN}✓ Output is not empty${NC}"
			echo "Total lines: $(wc -l < "$tempFile")"
		else
			echo -e "${RED}✗ Output is empty${NC}"
		fi
	else
		echo -e "${RED}✗ Command failed with exit code $exitCode${NC}"
		cat "$tempFile"
	fi

	# Clean up
	rm -f "$tempFile"
	echo "----------------------------------------"
}

echo "=================================================="
echo "Testing domains-list output formats"
echo "=================================================="

# Test each format
runFormatTest "Table (default)" "table"
runFormatTest "JSON" "json"
runFormatTest "Simple" "simple"
runFormatTest "CSV" "csv"

echo "=================================================="
echo "Format tests completed"
echo "=================================================="

# Test with user filter
echo "Testing user filter with each format..."

# Get a test username (first user in the system)
testUser=$(opencli user-list --format simple | head -n 1)

if [ -n "$testUser" ]; then
	echo "Using test user: $testUser"

	runFormatTest "Table with user filter" "table" "$testUser"
	runFormatTest "JSON with user filter" "json" "$testUser"
	runFormatTest "Simple with user filter" "simple" "$testUser"
	runFormatTest "CSV with user filter" "csv" "$testUser"
else
	echo -e "${RED}No users found for testing filters${NC}"
fi

echo "=================================================="
echo "All tests completed"
echo "=================================================="
