#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: tests/uninstall.test.sh
# Description: Unit tests for OpenCLI uninstall script
# Author: Generated by Copilot
################################################################################

# Include test framework
source "$(dirname "$0")/test_framework.sh"

# Mock functions to prevent actual system changes
mock_systemctl() {
	echo "MOCK: systemctl $*"
	return 0
}

mock_rm() {
	echo "MOCK: rm $*"
	return 0
}

mock_mkdir() {
	echo "MOCK: mkdir $*"
	return 0
}

mock_grep() {
	if [[ "$*" == *"openpanel"* ]]; then
		echo "MOCK: Found openpanel"
		return 0
	fi
	return 1
}

mock_mysql() {
	echo "MOCK: mysql $*"
	return 0
}

mock_apt_get() {
	echo "MOCK: apt-get $*"
	return 0
}

mock_yum() {
	echo "MOCK: yum $*"
	return 0
}

mock_lsb_release() {
	echo "ubuntu"
	return 0
}

setup() {
	# Create mock environment
	export MOCK_DIR=$(mktemp -d)

	# Set up mocks
	alias systemctl="mock_systemctl"
	alias rm="mock_rm"
	alias mkdir="mock_mkdir"
	alias grep="mock_grep"
	alias mysql="mock_mysql"
	alias apt-get="mock_apt_get"
	alias yum="mock_yum"
	alias lsb_release="mock_lsb_release"

	# Mock file existence checks
	export MOCK_FILES=(
		"/usr/local/bin/opencli"
		"/usr/local/opencli"
		"/etc/nginx/sites-enabled/openpanel-api.conf"
		"/etc/nginx/sites-available/openpanel-api.conf"
		"/etc/openpanel/openpanel/conf/openpanel.config"
		"/etc/openpanel/opencli"
		"/var/log/openpanel/admin"
		"/etc/openpanel/openadmin/api"
		"/etc/openpanel/openadmin/config/backups"
		"/tmp/opencli"
		"/tmp/openpanel_backups"
		"/etc/systemd/system/admin.service"
		"/etc/cron.d/openpanel_backups"
		"/root/.env"
	)

	# Source the uninstall script with functions only
	source /home/getsuper/opencli/uninstall.sh
}

teardown() {
	# Clean up mock environment
	rm -rf "$MOCK_DIR"
	unalias systemctl rm mkdir grep mysql apt-get yum lsb_release 2>/dev/null || true
	unset MOCK_FILES MOCK_DIR
}

# Test basic uninstall
test_basic_uninstall() {
	# Set up test
	PURGE=false
	KEEP_BACKUPS=false
	ASSUME_YES=true
	VERBOSE=false

	# Run the functions to test
	output=$(stop_services 2>&1)
	assert_contains "$output" "Stopping OpenCLI services"

	output=$(remove_opencli_files 2>&1)
	assert_contains "$output" "Removing OpenCLI files"

	output=$(remove_api_config 2>&1)
	assert_contains "$output" "Removing API configurations"

	output=$(remove_config_files 2>&1)
	assert_contains "$output" "Skipping removal of configuration files"

	output=$(handle_distro_specific 2>&1)
	assert_contains "$output" "Detected Debian-based system"
}

# Test purge uninstall
test_purge_uninstall() {
	# Set up test
	PURGE=true
	KEEP_BACKUPS=false
	ASSUME_YES=true
	VERBOSE=false

	# Run the functions to test
	output=$(remove_database_tables 2>&1)
	assert_contains "$output" "Removing OpenCLI database tables"

	output=$(remove_config_files 2>&1)
	assert_contains "$output" "Removing configuration files"

	output=$(remove_temp_files 2>&1)
	assert_contains "$output" "Cleaning up temporary files"
}

# Test keep backups option
test_keep_backups() {
	# Set up test
	PURGE=true
	KEEP_BACKUPS=true
	ASSUME_YES=true
	VERBOSE=false

	output=$(remove_config_files 2>&1)
	assert_contains "$output" "Keeping backup configurations as requested"
}

# Test OpenPanel detection
test_openpanel_detection() {
	output=$(check_openpanel 2>&1)
	OPENPANEL_INSTALLED=true

	output=$(stop_services 2>&1)
	assert_contains "$output" "OpenPanel is installed"
}

# Test distribution detection
test_distribution_detection() {
	output=$(handle_distro_specific 2>&1)
	assert_contains "$output" "Detected Debian-based system"
}

# Test verbose output
test_verbose_output() {
	VERBOSE=true
	output=$(print_status "info" "Test message" 2>&1)
	assert_contains "$output" "Test message"
}

# Run tests
run_test "Basic Uninstall" test_basic_uninstall
run_test "Purge Uninstall" test_purge_uninstall
run_test "Keep Backups Option" test_keep_backups
run_test "OpenPanel Detection" test_openpanel_detection
run_test "Distribution Detection" test_distribution_detection
run_test "Verbose Output" test_verbose_output

# Show test results
show_results
