#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: domains/list.sh
# Description: List all domains in the system
# Usage: opencli domains-list [--user username] [--format json|table|simple|csv]
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh

USER=""
FORMAT="table"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
	case "$1" in
		--user)
			USER="$2"
			shift 2
			;;
		--format)
			FORMAT="$2"
			shift 2
			;;
		--help)
			echo "Usage: opencli domains-list [--user username] [--format json|table|simple|csv]"
			echo ""
			echo "Options:"
			echo "  --user USERNAME    Filter domains by username"
			echo "  --format FORMAT    Output format: json, table, simple, or csv (default: table)"
			echo "                     'simple' outputs just domain names, one per line"
			echo "                     'csv' outputs data in comma-separated values format"
			echo "  --help             Show this help message and exit"
			exit 0
			;;
		*)
			echo "Unknown option: $1"
			echo "Use --help for usage information."
			exit 1
			;;
	esac
done

# Database connection parameters
DB_HOST=$(get_db_host)
DB_USER=$(get_db_user)
DB_PASS=$(get_db_password)
DB_NAME=$(get_db_name)

# Build the SQL query based on parameters
if [ -z "$USER" ]; then
	SQL_QUERY="SELECT domain, user, created_at, status FROM domains ORDER BY domain;"
else
	SQL_QUERY="SELECT domain, user, created_at, status FROM domains WHERE user='$USER' ORDER BY domain;"
fi

# Execute the query based on format
case "$FORMAT" in
	"json")
		# Output in JSON format
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "$SQL_QUERY" --skip-column-names | \
			awk 'BEGIN {print "{\"domains\": ["}
			{
				printf "  {\n    \"name\": \"%s\",\n    \"user\": \"%s\",\n    \"created_at\": \"%s\",\n    \"status\": \"%s\"\n  }", $1, $2, $3, $4;
				if (NR < rows) printf ",";
				printf "\n";
			}
			END {print "]}"}' rows=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "$SQL_QUERY" --skip-column-names | wc -l)
		;;
	"simple")
		# Output just domain names, one per line (useful for scripting)
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT domain FROM domains WHERE ${USER:+user='$USER'} 1=1 ORDER BY domain;" --skip-column-names
		;;
	"csv")
		# Output in CSV format for easy importing into spreadsheets
		echo "Domain,User,Created_At,Status"
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "$SQL_QUERY" --skip-column-names | \
			awk '{printf "%s,%s,%s,%s\n", $1, $2, $3, $4}'
		;;
	*)
		# Default to table format with improved formatting
		# Calculate column widths
		DOMAIN_WIDTH=30
		USER_WIDTH=15
		DATE_WIDTH=20

		# Print header with fixed width columns
		printf "\033[1m%-${DOMAIN_WIDTH}s\033[0m | \033[1m%-${USER_WIDTH}s\033[0m | \033[1m%-${DATE_WIDTH}s\033[0m | \033[1m%s\033[0m\n" "Domain" "User" "Created At" "Status"
		printf "%s\n" "$(printf '=%.0s' {1..80})"

		# Print each row with fixed width columns
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "$SQL_QUERY" --skip-column-names | \
			while read -r domain user created_at status; do
				# Truncate long values with ellipsis to maintain table alignment
				if [ ${#domain} -gt $((DOMAIN_WIDTH-3)) ]; then
					domain="${domain:0:$((DOMAIN_WIDTH-3))}..."
				fi

				if [ ${#user} -gt $((USER_WIDTH-3)) ]; then
					user="${user:0:$((USER_WIDTH-3))}..."
				fi

				printf "%-${DOMAIN_WIDTH}s | %-${USER_WIDTH}s | %-${DATE_WIDTH}s | %s\n" "$domain" "$user" "$created_at" "$status"
			done
		;;
esac

exit 0
