#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: api/backups.sh
# Description: RESTful API endpoints for managing backups
# Usage: Called via OpenPanel API gateway
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh
source /usr/local/opencli/functions/api.sh

# Get request headers
authHeader=$(grep -i "^Authorization:" /dev/stdin)

# Extract token from Authorization header
token=$(extract_token_from_header "$authHeader")
if [ -z "$token" ]; then
	send_error_response 401 "Authentication required"
	exit 1
fi

# Validate token
username=$(validate_api_token "$token")
if [ -z "$username" ]; then
	send_error_response 401 "Invalid or expired token"
	exit 1
fi

# Determine request method
request_method=${REQUEST_METHOD:-GET}
request_uri=${REQUEST_URI:-"/"}

# Check if user has admin privileges
is_admin=$(check_admin_privileges "$username")

# Extract target username from URL if present
target_user=$(echo "$request_uri" | grep -oP '/api/v1/backups/\K[a-zA-Z0-9_-]+$')

# If no target user specified and it's not a POST request for creating backup
if [ -z "$target_user" ] && ! [[ "$request_method" = "POST" && "$request_uri" = "/api/v1/backups" ]]; then
	send_error_response 400 "Username is required in URL path"
	exit 1
fi

# If target user is specified, check access permissions
if [ -n "$target_user" ]; then
	# Only allow if user is accessing their own backups or is admin
	if [ "$is_admin" != "true" ] && [ "$username" != "$target_user" ]; then
		send_error_response 403 "Insufficient privileges"
		exit 1
	fi

	# Verify user exists
	user_exists=$(opencli user-list --format simple | grep -w "^$target_user$")
	if [ -z "$user_exists" ]; then
		send_error_response 404 "User not found"
		exit 1
	fi
fi

# Handle different HTTP methods
case "$request_method" in
	GET)
		# List backups for a specific user
		backup_list_output=$(opencli backup-list "$target_user" --json 2>&1)

		if [ $? -ne 0 ]; then
			send_error_response 500 "Failed to retrieve backups: $backup_list_output"
			exit 1
		fi

		# Format the output as JSON
		# Note: This assumes backup-list --json already outputs valid JSON
		# We're just reformatting it to match our API schema

		backups=$(echo "$backup_list_output" | jq -r '.backups')

		# Create final response
		response="{"
		response="${response}\"backups\": ${backups}"
		response="${response}}"

		send_json_response "$response"
		;;

	POST)
		# Only allow backup creation if URL is /api/v1/backups
		if [ "$request_uri" != "/api/v1/backups" ]; then
			send_error_response 400 "Invalid URL for backup creation"
			exit 1
		}

		# Read request body
		read -r request_body

		# Parse JSON request body
		backup_user=$(echo "$request_body" | grep -o '"username":[^,}]*' | cut -d'"' -f4)
		backup_type=$(echo "$request_body" | grep -o '"type":[^,}]*' | cut -d'"' -f4)

		# Default to "full" if type not specified
		if [ -z "$backup_type" ]; then
			backup_type="full"
		fi

		# Validate inputs
		if [ -z "$backup_user" ]; then
			send_error_response 400 "Username is required"
			exit 1
		fi

		# Check if user exists
		user_exists=$(opencli user-list --format simple | grep -w "^$backup_user$")
		if [ -z "$user_exists" ]; then
			send_error_response 404 "User not found"
			exit 1
		fi

		# Check if requesting user is admin or the target user
		if [ "$is_admin" != "true" ] && [ "$username" != "$backup_user" ]; then
			send_error_response 403 "Insufficient privileges"
			exit 1
		}

		# Create backup
		backup_id="backup_${backup_user}_$(date +%Y%m%d_%H%M%S)"

		# Initiate backup in background to prevent API timeout
		(opencli backup-user "$backup_user" --type "$backup_type" > /dev/null 2>&1) &

		# Return response immediately
		send_json_response "{\"success\": true, \"message\": \"Backup for user $backup_user has been initiated\", \"backup_id\": \"$backup_id\"}"
		;;

	DELETE)
		# Extract backup ID from query parameters
		query_string=${QUERY_STRING:-""}
		backup_id=""

		if [[ "$query_string" =~ backup_id=([^&]+) ]]; then
			backup_id="${BASH_REMATCH[1]}"
		fi

		if [ -z "$backup_id" ]; then
			send_error_response 400 "backup_id parameter is required"
			exit 1
		}

		# Check if backup exists for the user
		backup_exists=$(opencli backup-list "$target_user" --json | jq -r ".backups | map(select(.id == \"$backup_id\")) | length")

		if [ "$backup_exists" -eq 0 ]; then
			send_error_response 404 "Backup not found"
			exit 1
		fi

		# Delete backup
		delete_output=$(opencli backup-delete "$target_user" "$backup_id" --force 2>&1)

		if [ $? -eq 0 ]; then
			send_json_response "{\"success\": true, \"message\": \"Backup $backup_id has been deleted\"}"
		else
			send_error_response 500 "Failed to delete backup: $delete_output"
		fi
		;;

	*)
		send_error_response 405 "Method not allowed"
		exit 1
		;;
esac

exit 0
