#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: api/gateway.sh
# Description: API Gateway for OpenCLI - routes requests to appropriate handlers
# Usage: Called by web server through CGI
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh
source /usr/local/opencli/functions/api.sh

# Set content type header as default
echo "Content-Type: application/json"

# Log API request if debug is enabled
if [ "$DEBUG" = true ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S') | API Request: $REQUEST_METHOD $REQUEST_URI" >> /var/log/openpanel/admin/api.log
fi

# Parse request URI
request_uri=${REQUEST_URI:-"/api/v1"}
request_method=${REQUEST_METHOD:-"GET"}

# Handle OPTIONS requests for CORS
if [ "$request_method" = "OPTIONS" ]; then
	echo "Access-Control-Allow-Origin: *"
	echo "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS"
	echo "Access-Control-Allow-Headers: Authorization, Content-Type"
	echo "Access-Control-Max-Age: 3600"
	echo ""
	exit 0
fi

# CORS headers for other requests
echo "Access-Control-Allow-Origin: *"
echo "Access-Control-Allow-Methods: GET, POST, PUT, DELETE"
echo "Access-Control-Allow-Headers: Authorization, Content-Type"

# Route request to appropriate handler based on URI path
if [[ "$request_uri" =~ ^/api/v1/domains(/.*)?$ ]]; then
	# Route to domains API handler
	bash /usr/local/opencli/api/domains.sh
elif [[ "$request_uri" =~ ^/api/v1/users(/.*)?$ ]]; then
	# Route to users API handler
	bash /usr/local/opencli/api/users.sh
elif [[ "$request_uri" =~ ^/api/v1/plans(/.*)?$ ]]; then
	# Route to plans API handler
	bash /usr/local/opencli/api/plans.sh
elif [[ "$request_uri" =~ ^/api/v1/php/(versions|install)$ ]]; then
	# Route to PHP API handler
	bash /usr/local/opencli/api/php.sh
elif [[ "$request_uri" =~ ^/api/v1/backups(/.*)?$ ]]; then
	# Route to backups API handler
	bash /usr/local/opencli/api/backups.sh
elif [[ "$request_uri" =~ ^/api/v1/system/(uninstall(/status/[^/]+)?|status|services)$ ]]; then
	# Route to system API handler
	bash /usr/local/opencli/api/system.sh
else
	# Handle unknown endpoints
	echo ""
	echo "{\"error\": \"Endpoint not found\", \"status\": 404}"

	if [ "$DEBUG" = true ]; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') | API Error: Endpoint not found - $request_uri" >> /var/log/openpanel/admin/api.log
	fi

	exit 1
fi
