#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: api/nginx-config.sh
# Description: Generates and installs Nginx configuration for OpenCLI API
# Usage: opencli api-nginx-config [--install]
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh

# Get server hostname or default
SERVER_NAME=$(hostname -f 2>/dev/null || echo "api.openpanel.local")

# Get API port or default to 8090
API_PORT=${API_PORT:-8090}

# Define the Nginx configuration template
generate_nginx_config() {
	cat << EOF
# OpenCLI API - Nginx Configuration
server {
	listen ${API_PORT};
	listen [::]:${API_PORT};

	server_name ${SERVER_NAME};

	access_log /var/log/nginx/openpanel-api-access.log;
	error_log /var/log/nginx/openpanel-api-error.log;

	# API Gateway
	location /api/ {
		root /usr/local/opencli/api;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME /usr/local/opencli/api/gateway.sh;
		fastcgi_param SCRIPT_NAME /api;
		fastcgi_param REQUEST_URI \$request_uri;
		fastcgi_param DOCUMENT_ROOT /usr/local/opencli/api;
		fastcgi_pass unix:/var/run/fcgiwrap.socket;
	}

	# API Documentation
	location /docs {
		alias /usr/local/opencli/docs;
		index api-reference.md;

		location ~* \.(md)\$ {
			default_type text/plain;
		}
	}

	# Nginx status for monitoring
	location /nginx-status {
		stub_status on;
		access_log off;
		allow 127.0.0.1;
		deny all;
	}

	# Redirect root to docs
	location = / {
		return 302 /docs/api-reference.md;
	}
}
EOF
}

# Display the configuration
generate_nginx_config

# Install if requested
if [ "$1" = "--install" ]; then
	# Check if running as root
	if [ "$(id -u)" != "0" ]; then
		echo "Error: This script must be run as root when using --install"
		exit 1
	fi

	# Check if nginx is installed
	if ! command -v nginx &> /dev/null; then
		echo "Error: Nginx is not installed"
		exit 1
	fi

	# Check if fcgiwrap is installed
	if ! command -v fcgiwrap &> /dev/null; then
		echo "Installing fcgiwrap..."
		apt-get update && apt-get install -y fcgiwrap
	fi

	# Make gateway script executable
	chmod +x /usr/local/opencli/api/gateway.sh

	# Create Nginx configuration file
	NGINX_CONF_FILE="/etc/nginx/sites-available/openpanel-api.conf"
	generate_nginx_config > "$NGINX_CONF_FILE"

	# Create symlink if it doesn't exist
	if [ ! -f "/etc/nginx/sites-enabled/openpanel-api.conf" ]; then
		ln -s "$NGINX_CONF_FILE" "/etc/nginx/sites-enabled/"
	fi

	# Test Nginx configuration
	nginx -t

	if [ $? -eq 0 ]; then
		# Reload Nginx if the test passed
		systemctl reload nginx
		echo "OpenCLI API configuration has been installed and Nginx reloaded"
		echo "API is now available at: http://${SERVER_NAME}:${API_PORT}/api/v1"
		echo "Documentation is available at: http://${SERVER_NAME}:${API_PORT}/docs"
	else
		echo "Error: Nginx configuration test failed. Please check the configuration manually."
	fi
fi
