#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: api/php.sh
# Description: RESTful API endpoints for managing PHP versions
# Usage: Called via OpenPanel API gateway
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh
source /usr/local/opencli/functions/api.sh

# Get request headers
authHeader=$(grep -i "^Authorization:" /dev/stdin)

# Extract token from Authorization header
token=$(extract_token_from_header "$authHeader")
if [ -z "$token" ]; then
	send_error_response 401 "Authentication required"
	exit 1
fi

# Validate token
username=$(validate_api_token "$token")
if [ -z "$username" ]; then
	send_error_response 401 "Invalid or expired token"
	exit 1
fi

# Determine request method
request_method=${REQUEST_METHOD:-GET}
request_uri=${REQUEST_URI:-"/"}

# Parse URL to determine action
if [[ "$request_uri" =~ /api/v1/php/versions ]]; then
	action="list_versions"
elif [[ "$request_uri" =~ /api/v1/php/install ]]; then
	action="install_version"
else
	send_error_response 404 "Endpoint not found"
	exit 1
fi

case "$request_method" in
	GET)
		if [ "$action" = "list_versions" ]; then
			# Parse query parameters to check for specific user
			query_string=${QUERY_STRING:-""}
			user_filter=""

			if [[ "$query_string" =~ user=([^&]+) ]]; then
				user_filter="${BASH_REMATCH[1]}"

				# Verify user exists
				user_exists=$(opencli user-list --format simple | grep -w "^$user_filter$")
				if [ -z "$user_exists" ]; then
					send_error_response 404 "User not found"
					exit 1
				fi
			fi

			# Get available PHP versions
			available_versions=$(opencli php-available_versions --format json | jq -r '.available_versions[]')

			# Format available versions array
			json_available_versions="["
			first=true
			for version in $available_versions; do
				if [ "$first" = true ]; then
					first=false
				else
					json_available_versions="${json_available_versions},"
				fi
				json_available_versions="${json_available_versions}\"$version\""
			done
			json_available_versions="${json_available_versions}]"

			# Get installed PHP versions for specific user if provided
			json_installed_versions="{"
			if [ -n "$user_filter" ]; then
				installed_versions=$(opencli php-installed_versions "$user_filter" --format json 2>/dev/null)
				if [ $? -eq 0 ] && [ -n "$installed_versions" ]; then
					user_versions=$(echo "$installed_versions" | jq -r '.installed_versions[]' 2>/dev/null)

					json_installed_versions="${json_installed_versions}\"$user_filter\": ["
					first=true
					for version in $user_versions; do
						if [ "$first" = true ]; then
							first=false
						else
							json_installed_versions="${json_installed_versions},"
						fi
						json_installed_versions="${json_installed_versions}\"$version\""
					done
					json_installed_versions="${json_installed_versions}]"
				else
					json_installed_versions="${json_installed_versions}\"$user_filter\": []"
				fi
			else
				# Get all users and their PHP versions
				users=$(opencli user-list --format simple)
				first_user=true

				for user in $users; do
					installed_versions=$(opencli php-installed_versions "$user" --format json 2>/dev/null)
					if [ $? -eq 0 ] && [ -n "$installed_versions" ]; then
						user_versions=$(echo "$installed_versions" | jq -r '.installed_versions[]' 2>/dev/null)

						if [ -n "$user_versions" ]; then
							if [ "$first_user" = true ]; then
								first_user=false
							else
								json_installed_versions="${json_installed_versions},"
							fi

							json_installed_versions="${json_installed_versions}\"$user\": ["
							first=true
							for version in $user_versions; do
								if [ "$first" = true ]; then
									first=false
								else
									json_installed_versions="${json_installed_versions},"
								fi
								json_installed_versions="${json_installed_versions}\"$version\""
							done
							json_installed_versions="${json_installed_versions}]"
						fi
					fi
				done
			fi
			json_installed_versions="${json_installed_versions}}"

			# Combine into final response
			response="{"
			response="${response}\"available_versions\": ${json_available_versions},"
			response="${response}\"installed_versions\": ${json_installed_versions}"
			response="${response}}"

			send_json_response "$response"
		else
			send_error_response 400 "Invalid action"
		fi
		;;

	POST)
		if [ "$action" = "install_version" ]; then
			# Check if the request is authorized for admin
			is_admin=$(check_admin_privileges "$username")

			# Read request body
			read -r request_body

			# Parse JSON request body
			target_user=$(echo "$request_body" | grep -o '"username":[^,}]*' | cut -d'"' -f4)
			php_version=$(echo "$request_body" | grep -o '"version":[^,}]*' | cut -d'"' -f4)

			# Validate inputs
			if [ -z "$target_user" ] || [ -z "$php_version" ]; then
				send_error_response 400 "Missing required parameters: username and version"
				exit 1
			fi

			# Check if user exists
			user_exists=$(opencli user-list --format simple | grep -w "^$target_user$")
			if [ -z "$user_exists" ]; then
				send_error_response 404 "User not found"
				exit 1
			fi

			# Check if requesting user is admin or the target user
			if [ "$is_admin" != "true" ] && [ "$username" != "$target_user" ]; then
				send_error_response 403 "Insufficient privileges"
				exit 1
			}

			# Verify PHP version is valid
			valid_version=$(opencli php-available_versions --format json | jq -r ".available_versions | index(\"$php_version\")")
			if [ "$valid_version" = "null" ]; then
				send_error_response 400 "Invalid PHP version"
				exit 1
			fi

			# Check if version is already installed
			installed_versions=$(opencli php-installed_versions "$target_user" --format json 2>/dev/null)
			if [ $? -eq 0 ] && [ -n "$installed_versions" ]; then
				already_installed=$(echo "$installed_versions" | jq -r ".installed_versions | index(\"$php_version\")")
				if [ "$already_installed" != "null" ]; then
					send_json_response "{\"success\": true, \"message\": \"PHP $php_version is already installed for user $target_user\"}"
					exit 0
				fi
			fi

			# Install PHP version
			install_output=$(opencli php-install "$target_user" "$php_version" 2>&1)

			if [ $? -eq 0 ]; then
				send_json_response "{\"success\": true, \"message\": \"PHP $php_version has been installed for user $target_user\"}"
			else
				send_error_response 500 "Installation failed: $install_output"
			fi
		else
			send_error_response 400 "Invalid action"
		fi
		;;

	*)
		send_error_response 405 "Method not allowed"
		exit 1
		;;
esac

exit 0
