#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: api/plans.sh
# Description: RESTful API endpoints for managing hosting plans
# Usage: Called via OpenPanel API gateway
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh
source /usr/local/opencli/functions/api.sh

# Get request headers
authHeader=$(grep -i "^Authorization:" /dev/stdin)

# Extract token from Authorization header
token=$(extract_token_from_header "$authHeader")
if [ -z "$token" ]; then
	send_error_response 401 "Authentication required"
	exit 1
fi

# Validate token
username=$(validate_api_token "$token")
if [ -z "$username" ]; then
	send_error_response 401 "Invalid or expired token"
	exit 1
fi

# Check if user has admin privileges
is_admin=$(check_admin_privileges "$username")
if [ "$is_admin" != "true" ]; then
	send_error_response 403 "Insufficient privileges"
	exit 1
fi

# Determine request method
request_method=${REQUEST_METHOD:-GET}
request_uri=${REQUEST_URI:-"/"}

# Database connection parameters
DB_HOST=$(get_db_host)
DB_USER=$(get_db_user)
DB_PASS=$(get_db_password)
DB_NAME=$(get_db_name)

# Extract plan_id from URL if present
plan_id=$(echo "$request_uri" | grep -oP '/api/v1/plans/\K[0-9]+$')

# Handle different HTTP methods
case "$request_method" in
	GET)
		# List all plans
		if [ -z "$plan_id" ]; then
			result=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT * FROM plans" --skip-column-names)

			# Format as JSON
			json="{"
			json="${json}\"plans\": ["

			first=true
			while IFS=$'\t' read -r id name description email_limit ftp_limit domains_limit websites_limit disk_limit inodes_limit db_limit cpu ram docker_image bandwidth; do
				if [ "$first" = true ]; then
					first=false
				else
					json="${json},"
				fi

				json="${json}{\"id\": $id, \"name\": \"$name\", \"description\": \"$description\", \"email_limit\": $email_limit, \"ftp_limit\": $ftp_limit, \"domains_limit\": $domains_limit, \"websites_limit\": $websites_limit, \"disk_limit\": \"$disk_limit\", \"inodes_limit\": $inodes_limit, \"db_limit\": $db_limit, \"cpu\": $cpu, \"ram\": \"$ram\", \"docker_image\": \"$docker_image\", \"bandwidth\": $bandwidth}"
			done <<< "$result"

			json="${json}]"
			json="${json}}"

			send_json_response "$json"
		else
			# Get specific plan by ID
			result=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT * FROM plans WHERE id=$plan_id" --skip-column-names)

			if [ -z "$result" ]; then
				send_error_response 404 "Plan not found"
				exit 1
			fi

			# Parse result into variables
			read -r id name description email_limit ftp_limit domains_limit websites_limit disk_limit inodes_limit db_limit cpu ram docker_image bandwidth <<< "$result"

			# Format as JSON
			json="{"
			json="${json}\"id\": $id, \"name\": \"$name\", \"description\": \"$description\", \"email_limit\": $email_limit, \"ftp_limit\": $ftp_limit, \"domains_limit\": $domains_limit, \"websites_limit\": $websites_limit, \"disk_limit\": \"$disk_limit\", \"inodes_limit\": $inodes_limit, \"db_limit\": $db_limit, \"cpu\": $cpu, \"ram\": \"$ram\", \"docker_image\": \"$docker_image\", \"bandwidth\": $bandwidth"
			json="${json}}"

			send_json_response "$json"
		fi
		;;

	POST)
		# Create a new plan
		# Read request body
		read -r request_body

		# Parse JSON request body
		name=$(echo "$request_body" | grep -o '"name":[^,}]*' | cut -d'"' -f4)
		description=$(echo "$request_body" | grep -o '"description":[^,}]*' | cut -d'"' -f4)
		email_limit=$(echo "$request_body" | grep -o '"email_limit":[^,}]*' | cut -d':' -f2)
		ftp_limit=$(echo "$request_body" | grep -o '"ftp_limit":[^,}]*' | cut -d':' -f2)
		domains_limit=$(echo "$request_body" | grep -o '"domains_limit":[^,}]*' | cut -d':' -f2)
		websites_limit=$(echo "$request_body" | grep -o '"websites_limit":[^,}]*' | cut -d':' -f2)
		disk_limit=$(echo "$request_body" | grep -o '"disk_limit":[^,}]*' | cut -d':' -f2)
		inodes_limit=$(echo "$request_body" | grep -o '"inodes_limit":[^,}]*' | cut -d':' -f2)
		db_limit=$(echo "$request_body" | grep -o '"db_limit":[^,}]*' | cut -d':' -f2)
		cpu=$(echo "$request_body" | grep -o '"cpu":[^,}]*' | cut -d':' -f2)
		ram=$(echo "$request_body" | grep -o '"ram":[^,}]*' | cut -d':' -f2)
		docker_image=$(echo "$request_body" | grep -o '"docker_image":[^,}]*' | cut -d'"' -f4)
		bandwidth=$(echo "$request_body" | grep -o '"bandwidth":[^,}]*' | cut -d':' -f2)

		# Format disk_limit with 'GB'
		disk_limit="${disk_limit} GB"

		# Format ram with 'g' at the end
		ram="${ram}g"

		# Set docker_image with openpanel prefix if needed
		case "$docker_image" in
			"nginx")
				docker_image="openpanel/nginx"
				;;
			"apache")
				docker_image="openpanel/apache"
				;;
			"litespeed")
				docker_image="openpanel/litespeed"
				;;
		esac

		# Insert the plan into the database
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "INSERT INTO plans (name, description, email_limit, ftp_limit, domains_limit, websites_limit, disk_limit, inodes_limit, db_limit, cpu, ram, docker_image, bandwidth) VALUES ('$name', '$description', $email_limit, $ftp_limit, $domains_limit, $websites_limit, '$disk_limit', $inodes_limit, $db_limit, $cpu, '$ram', '$docker_image', $bandwidth);"

		new_id=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT LAST_INSERT_ID();" --skip-column-names)

		# Form response
		response="{\"success\": true, \"message\": \"Plan '$name' has been created\", \"plan\": {\"id\": $new_id, \"name\": \"$name\", \"description\": \"$description\", \"email_limit\": $email_limit, \"ftp_limit\": $ftp_limit, \"domains_limit\": $domains_limit, \"websites_limit\": $websites_limit, \"disk_limit\": \"$disk_limit\", \"inodes_limit\": $inodes_limit, \"db_limit\": $db_limit, \"cpu\": $cpu, \"ram\": \"$ram\", \"docker_image\": \"$docker_image\", \"bandwidth\": $bandwidth}}"

		send_json_response "$response"
		;;

	PUT)
		# Update an existing plan
		if [ -z "$plan_id" ]; then
			send_error_response 400 "Plan ID required"
			exit 1
		fi

		# Check if plan exists
		plan_exists=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT COUNT(*) FROM plans WHERE id=$plan_id" --skip-column-names)

		if [ "$plan_exists" -eq 0 ]; then
			send_error_response 404 "Plan not found"
			exit 1
		fi

		# Read request body
		read -r request_body

		# Parse JSON request body
		name=$(echo "$request_body" | grep -o '"name":[^,}]*' | cut -d'"' -f4)
		description=$(echo "$request_body" | grep -o '"description":[^,}]*' | cut -d'"' -f4)
		email_limit=$(echo "$request_body" | grep -o '"email_limit":[^,}]*' | cut -d':' -f2)
		ftp_limit=$(echo "$request_body" | grep -o '"ftp_limit":[^,}]*' | cut -d':' -f2)
		domains_limit=$(echo "$request_body" | grep -o '"domains_limit":[^,}]*' | cut -d':' -f2)
		websites_limit=$(echo "$request_body" | grep -o '"websites_limit":[^,}]*' | cut -d':' -f2)
		disk_limit=$(echo "$request_body" | grep -o '"disk_limit":[^,}]*' | cut -d':' -f2)
		inodes_limit=$(echo "$request_body" | grep -o '"inodes_limit":[^,}]*' | cut -d':' -f2)
		db_limit=$(echo "$request_body" | grep -o '"db_limit":[^,}]*' | cut -d':' -f2)
		cpu=$(echo "$request_body" | grep -o '"cpu":[^,}]*' | cut -d':' -f2)
		ram=$(echo "$request_body" | grep -o '"ram":[^,}]*' | cut -d':' -f2)
		docker_image=$(echo "$request_body" | grep -o '"docker_image":[^,}]*' | cut -d'"' -f4)
		bandwidth=$(echo "$request_body" | grep -o '"bandwidth":[^,}]*' | cut -d':' -f2)

		# Format disk_limit with 'GB'
		disk_limit="${disk_limit} GB"

		# Format ram with 'g' at the end
		ram="${ram}g"

		# Set docker_image with openpanel prefix if needed
		case "$docker_image" in
			"nginx")
				docker_image="openpanel/nginx"
				;;
			"apache")
				docker_image="openpanel/apache"
				;;
			"litespeed")
				docker_image="openpanel/litespeed"
				;;
		esac

		# Update the plan in the database
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "UPDATE plans SET name='$name', description='$description', email_limit=$email_limit, ftp_limit=$ftp_limit, domains_limit=$domains_limit, websites_limit=$websites_limit, disk_limit='$disk_limit', inodes_limit=$inodes_limit, db_limit=$db_limit, cpu=$cpu, ram='$ram', docker_image='$docker_image', bandwidth=$bandwidth WHERE id=$plan_id"

		# Form response
		response="{\"success\": true, \"message\": \"Plan has been updated\", \"plan\": {\"id\": $plan_id, \"name\": \"$name\", \"description\": \"$description\", \"email_limit\": $email_limit, \"ftp_limit\": $ftp_limit, \"domains_limit\": $domains_limit, \"websites_limit\": $websites_limit, \"disk_limit\": \"$disk_limit\", \"inodes_limit\": $inodes_limit, \"db_limit\": $db_limit, \"cpu\": $cpu, \"ram\": \"$ram\", \"docker_image\": \"$docker_image\", \"bandwidth\": $bandwidth}}"

		send_json_response "$response"
		;;

	DELETE)
		# Delete a plan
		if [ -z "$plan_id" ]; then
			send_error_response 400 "Plan ID required"
			exit 1
		fi

		# Check if plan exists
		plan_name=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT name FROM plans WHERE id=$plan_id" --skip-column-names)

		if [ -z "$plan_name" ]; then
			send_error_response 404 "Plan not found"
			exit 1
		fi

		# Check if plan is in use
		users_count=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT COUNT(*) FROM users WHERE plan_id=$plan_id" --skip-column-names)

		if [ "$users_count" -gt 0 ]; then
			send_error_response 409 "Plan is in use by $users_count users and cannot be deleted"
			exit 1
		}

		# Delete the plan
		mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "DELETE FROM plans WHERE id=$plan_id"

		# Form response
		response="{\"success\": true, \"message\": \"Plan '$plan_name' has been deleted\"}"

		send_json_response "$response"
		;;

	*)
		send_error_response 405 "Method not allowed"
		exit 1
		;;
esac

exit 0
