#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: api/system.sh
# Description: RESTful API endpoints for system operations including uninstall
# Usage: Called via OpenPanel API gateway
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh
source /usr/local/opencli/functions/api.sh

# Get request headers
authHeader=$(grep -i "^Authorization:" /dev/stdin)

# Extract token from Authorization header
token=$(extract_token_from_header "$authHeader")
if [ -z "$token" ]; then
	send_error_response 401 "Authentication required"
	exit 1
fi

# Validate token
username=$(validate_api_token "$token")
if [ -z "$username" ]; then
	send_error_response 401 "Invalid or expired token"
	exit 1
fi

# Check if user has admin privileges
is_admin=$(check_admin_privileges "$username")
if [ "$is_admin" != "true" ]; then
	send_error_response 403 "Insufficient privileges"
	exit 1
fi

# Determine request method
request_method=${REQUEST_METHOD:-GET}
request_uri=${REQUEST_URI:-"/"}

# Extract job_id from URL if present for status endpoint
job_id=""
if [[ "$request_uri" =~ /api/v1/system/uninstall/status/([^/]+) ]]; then
	job_id="${BASH_REMATCH[1]}"
fi

# Handle different HTTP methods and endpoints
if [[ "$request_uri" = "/api/v1/system/uninstall" ]]; then
	if [ "$request_method" = "POST" ]; then
		# Process uninstall request

		# Read request body
		read -r request_body

		# Parse JSON request body
		purge=false
		if echo "$request_body" | grep -q '"purge":true'; then
			purge=true
		fi

		keep_backups=false
		if echo "$request_body" | grep -q '"keep_backups":true'; then
			keep_backups=true
		fi

		# Generate unique job ID
		current_date=$(date +%Y%m%d_%H%M%S)
		job_id="uninstall_${current_date}"

		# Create log directory for the job
		job_dir="/var/log/openpanel/admin/jobs/${job_id}"
		mkdir -p "$job_dir"

		# Store job parameters
		cat > "${job_dir}/params.json" << EOF
{
	"job_id": "${job_id}",
	"status": "pending",
	"progress": 0,
	"message": "Uninstall job created",
	"purge": ${purge},
	"keep_backups": ${keep_backups},
	"created_at": "$(date -Iseconds)",
	"completed_steps": [],
	"remaining_steps": ["stop_services", "remove_opencli_files", "remove_api_config", "remove_database_tables", "remove_config_files", "cleanup_system"],
	"error": null
}
EOF

		# Run uninstall in background
		(
			# Update status to in_progress
			jq '.status="in_progress" | .message="Starting uninstall process"' "${job_dir}/params.json" > "${job_dir}/params.json.tmp" && mv "${job_dir}/params.json.tmp" "${job_dir}/params.json"

			# Start uninstall with provided options
			options=""
			if [ "$purge" = true ]; then
				options="--purge"
			fi

			if [ "$keep_backups" = true ]; then
				options="$options --keep-backups"
			fi

			# Run uninstall with --yes to skip confirmation prompts
			bash /usr/local/opencli/uninstall.sh $options --yes > "${job_dir}/output.log" 2>&1

			# Check result
			if [ $? -eq 0 ]; then
				jq '.status="completed" | .progress=100 | .message="Uninstallation completed successfully" | .remaining_steps=[]' "${job_dir}/params.json" > "${job_dir}/params.json.tmp" && mv "${job_dir}/params.json.tmp" "${job_dir}/params.json"
			else
				error_msg=$(tail -n 5 "${job_dir}/output.log" | tr -d '\n' | sed 's/"/\\"/g')
				jq --arg error "$error_msg" '.status="failed" | .error=$error | .message="Uninstallation failed"' "${job_dir}/params.json" > "${job_dir}/params.json.tmp" && mv "${job_dir}/params.json.tmp" "${job_dir}/params.json"
			fi
		) &

		# Send immediate response
		send_json_response "{\"success\": true, \"message\": \"Uninstallation process has been initiated\", \"job_id\": \"${job_id}\"}"

	else
		send_error_response 405 "Method not allowed"
	fi

elif [[ "$request_uri" =~ /api/v1/system/uninstall/status/ ]]; then
	if [ "$request_method" = "GET" ]; then
		# Check if job exists
		job_params_file="/var/log/openpanel/admin/jobs/${job_id}/params.json"

		if [ ! -f "$job_params_file" ]; then
			send_error_response 404 "Uninstall job not found"
			exit 1
		fi

		# Read and return job status
		job_status=$(cat "$job_params_file")
		send_json_response "$job_status"
	else
		send_error_response 405 "Method not allowed"
	fi

else
	send_error_response 404 "Endpoint not found"
fi

exit 0
