#!/bin/bash
# Generated by Copilot

################################################################################
# Script Name: api/token-generate.sh
# Description: Generate API token for authenticating with OpenCLI API
# Usage: opencli api-token-generate [--user username] [--expiry days]
# Author: Generated by Copilot
################################################################################

source /usr/local/opencli/functions.sh

# Default values
USERNAME=""
EXPIRY=30 # Default token expiry in days

# Parse command line arguments
while [[ $# -gt 0 ]]; do
	case "$1" in
		--user)
			USERNAME="$2"
			shift 2
			;;
		--expiry)
			EXPIRY="$2"
			shift 2
			;;
		--help)
			echo "Usage: opencli api-token-generate [--user username] [--expiry days]"
			echo ""
			echo "Options:"
			echo "  --user USERNAME    Generate token for specific user (admin only)"
			echo "  --expiry DAYS      Token expiry in days (default: 30)"
			echo "  --help             Show this help message"
			exit 0
			;;
		*)
			echo "Unknown option: $1"
			echo "Use --help for usage information."
			exit 1
			;;
	esac
done

# Check if running as root or specific user is requested
if [ -z "$USERNAME" ]; then
	# If no specific user, get current username
	CURRENT_USER=$(whoami)
	if [ "$CURRENT_USER" = "root" ]; then
		echo "Error: When running as root, you must specify a user with --user"
		exit 1
	fi
	USERNAME="$CURRENT_USER"
else
	# If specific user requested, only root can do this
	if [ "$(id -u)" -ne 0 ]; then
		echo "Error: Only root can generate tokens for other users"
		exit 1
	fi

	# Verify the requested user exists
	if ! user_exists "$USERNAME"; then
		echo "Error: User '$USERNAME' does not exist"
		exit 1
	fi
fi

# Database connection
DB_HOST=$(get_db_host)
DB_USER=$(get_db_user)
DB_PASS=$(get_db_password)
DB_NAME=$(get_db_name)

# Generate a secure random token (32 bytes, base64 encoded)
TOKEN=$(openssl rand -base64 32 | tr -d '/+=' | cut -c1-32)

# Calculate expiry date
EXPIRY_DATE=$(date -d "+$EXPIRY days" +"%Y-%m-%d %H:%M:%S")

# Store token in database
# First check if api_tokens table exists, create if not
mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "
CREATE TABLE IF NOT EXISTS api_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  token VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  last_used DATETIME,
  UNIQUE KEY (token)
);"

# Insert the new token
mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "
INSERT INTO api_tokens (username, token, created_at, expires_at)
VALUES ('$USERNAME', '$TOKEN', NOW(), '$EXPIRY_DATE');"

if [ $? -eq 0 ]; then
	echo "API token generated successfully for user: $USERNAME"
	echo "Token: $TOKEN"
	echo "Expires: $EXPIRY_DATE"
	echo ""
	echo "Include this token in your API requests with the HTTP header:"
	echo "Authorization: Bearer $TOKEN"
	echo ""
	echo "Important: Store this token securely. It will not be displayed again."
else
	echo "Error: Failed to generate API token"
	exit 1
fi

exit 0
